### ISSUE TITLE
Meaningful difference map without (or with minimal) Refmac refinement

### ISSUE THREAD

**Issue by helgepat** [keitaroyam/servalcat#4] opened 2022-01-27 13:01 UTC
Hi,
I now have succesfully used servalcat for generating a difference map through the "refine_spa" option.
I have to say, I find the resulting diffmap highly useful, it helped me tremendously in identifying and modelling my ligand of interest.
What I noticed though, is that there are some issues with the restraints that result in damaged geometry of some modified RNA residues after the Refmac refinement (looking at "refined.mmcif"). This means that there are red/green clusters in the diffmap where it has gone wrong, whereas my original model has the correct (parental) fit for these residues.
While I realize that this could probably be fixed by repairing the restraints file (which I do not really know how to do), I wanted to inquire if it is possible to generate a diffmap with a minimal refinement that would not touch these residues. I understand that Refmac has to be run to generate a meaningful diffmap, but I was wondering if there are different job options that could be tried here. 
Also, it is a bit weird, as Coot seems to be able to handle my current restraints, at least without moving the residues in question too much and out of density (as Refmac does).
Best, and many thanks for reading!

**Comment by keitaroyam** [comment] 2022-01-27 20:30
Thank you for your feedback. Is it only about the modified RNA residues? Did you give their restraint cif files (in this case how did you prepare), or were they included in CCP4 monomer library?

Refinement of atomic B values is essential to calculate meaningful difference map. So you may want to fix coordinates. There are two options:
1. Use harmonic restraint not to move atoms much; can be done with e.g. `--keywords "external harmonic residues from 225 A to 250 A sigma 0.02"` 
2. Refine B only; with `--keywords "refi bonly"`

Option 1 needs a selection. Details can be found here: https://www2.mrc-lmb.cam.ac.uk/groups/murshudov/content/refmac/refmac_keywords.html#id.cc427fd5ac11

While these options may be useful, I would like to find the cause of this problem. Possible causes:
* problem in restraint files (but it is ok with COOT?)
* inappropriate geometry weight in Refmac (what was bond rmsd after refinement?)
* maybe because of riding hydrogen atoms (can be turned off with `--hydrogen no`)
* others?

**Comment by helgepat** [comment] 2022-01-27 22:11
OK, I have looked at it again and it turns out that I can only find one occurence of the issue in the model at the moment. Maybe, I saw the same spot multiple times in different iterations of it... Anyway, it is not RNA as thought, but in a protein chain where two modified residues are directly adjacent (4D4 and MS6). I guess it has something to do with restraints missing for the linkage of these two?
I prepared the residues, as you suggested previously, from the .cif files I obtained from PDB Expo using acedrg.
I checked again in Coot with Sphere Refine and also here the residues are not linked, I can pull out the individual modified residues. Coot does not seem to move those around too much in Real Space Refinement, thats why it appeared to me that it can handle them better.

**Comment by keitaroyam** [comment] 2022-01-28 00:33
~~Is MS6 actually what you meant? It does not seem to be an amino acid https://www.rcsb.org/ligand/MS6.~~
OK now I know what you mean. I will shortly get back to you.

For linking, I think it is related to recent change in PDB monomer definitions. If you look at the first lines of acedrg_4D4.cif,
```
data_comp_list
loop_
_chem_comp.id
_chem_comp.three_letter_code
_chem_comp.name
_chem_comp.group
_chem_comp.number_atoms_all
_chem_comp.number_atoms_nh
_chem_comp.desc_level
4D4     4D4      "(2S,3R)-2-azanyl-5-carbamimidamido-3-oxidanyl-pentanoic acid"     "L-peptide linking"     28     13     .
```
do you see the same thing? Then please replace `"L-peptide linking"` with `peptide`. I think COOT will work with this. Refmac ~~may need link information, but please try (I also need to check it)~~ should also work, but 4D4-MS6 needs a link definition.

**Comment by keitaroyam** [comment] 2022-01-31 10:18
This is indeed interesting. I see MS6 forms thioamide in the main chain. You need to create link definitions for 4D4-MS6 and MS6-GLY.

Save the following line as 4D4-MS6.txt
```
LINK: RES-NAME-1 4D4 FILE-1 acedrg_4D4.cif ATOM-NAME-1  C  RES-NAME-2 MS6 FILE-2 acedrg_MS6.cif ATOM-NAME-2  N1 DELETE ATOM O1 1
```
and run:
```
acedrg -L 4D4-MS6.txt ​-o 4D4-MS6
```
then you will get `4D4-MS6_link.cif`.

Next, save this as MS6-GLY.txt
```
LINK: RES-NAME-1 MS6 FILE-1 acedrg_MS6.cif ATOM-NAME-1  C  RES-NAME-2 GLY ATOM-NAME-2 N DELETE ATOM OXT 1 CHANGE BOND C S DOUBLE 1
```
and run
```
acedrg -L MS6-GLY.txt ​-o MS6-GLY
```
to get `MS6-GLY_link.cif`.

Please give these link cif files to `--ligand` in servalcat. Alternatively you can use [4D4-MS6-GLY_merged.zip](https://github.com/keitaroyam/servalcat/files/7969876/4D4-MS6-GLY_merged.zip) I generated using the commands above (and merged).

In addition, you need following lines in the input PDB header to tell Refmac to make these links. I just added a code to automatically add these lines (you need to update servalcat from github).
```
LINKR        C   4D4 l  81                 N1  MS6 l  82                4D4-MS6
LINKR        C   MS6 l  82                 N   GLY l  83                MS6-GLY
```

I will make MS6-pept link and try to put it to CCP4 monomer library so that you do not have to do this in future.

**Comment by helgepat** [comment] 2022-01-31 10:32
Thanks so much for the input! I will try to look into this tonight, but what you write sounds promising!

**Comment by keitaroyam** [comment] 2022-01-31 11:35
One more thing, probably the current Refmac5 in CCP4 7.1 has a bug in writing mmcif (long compound names lead to a broken mmcif file).

You may need to shorten compound names in the cif file. For example, in the following cif files, `"(2S,3R)-2-azanyl-5-carbamimidamido-3-oxidanyl-pentanoic acid"` and `"(2S)-2-amino-4-(methylsulfanyl)butane-1-thiol"` should be replaced with much shorter names (like `"(3R)-3-hydroxy-L-arginine"` or just `""`)
```
data_comp_list
loop_
_chem_comp.id
_chem_comp.three_letter_code
_chem_comp.name
_chem_comp.group
_chem_comp.number_atoms_all
_chem_comp.number_atoms_nh
_chem_comp.desc_level
4D4 4D4 "(2S,3R)-2-azanyl-5-carbamimidamido-3-oxidanyl-pentanoic acid" peptide 28 13 .
MS6 MS6 "(2S)-2-amino-4-(methylsulfanyl)butane-1-thiol" non-polymer 21 8 .

...

data_mod_list
loop_
_chem_mod.id
_chem_mod.name
_chem_mod.comp_id
_chem_mod.group_id
4D4m1 "(2S,3R)-2-azanyl-5-carbamimidamido-3-oxidanyl-pentanoic acid" 4D4 .
MS6m1 "(2S)-2-amino-4-(methylsulfanyl)butane-1-thiol" MS6 .
MS6m1-2 "(2S)-2-amino-4-(methylsulfanyl)butane-1-thiol" MS6 .
GLYm1 GLYCINE GLY .
```

Sorry for the inconvenience. This bug is fixed in the latest code of Refmac5 (but not yet released in CCP4).

**Comment by helgepat** [comment] 2022-01-31 21:46
OK, I have modified all my previous restraints by changing "L-peptide linking" with "peptide" and replacing the names with "". I have also saved my model as .pdb and added the LINKR records (How would I do that in a .cif file btw?). 
I can already say that loading all these in Coot does not work, i. e. there are no links between the monomers.
I just installed the newest servalcat on a different workstation and am running the job at the moment (WIth the linked restraints, but also the corresponding monomers in the "cif" folder).
I think I am beginning to understand how to make my own custom link restraints in the future, so thank you again for the explanation, but I have one question for this:
The model in PDB7K00 contains one gamma-linked residue (IAS K119) which I have currently mutated to ASP in my model, as I was not sure how to handle the restraint. Do you have any idea what I would have to put here to make it work? Just running acedrg and using the resulting restraints does not seem to work in Coot.

**Comment by keitaroyam** [comment] 2022-01-31 23:56
LINK(R) records in PDB file correspond to `_struct_conn` in mmcif file. It would be like this (this is written by Servalcat):
```
loop_
_struct_conn.id
_struct_conn.conn_type_id
_struct_conn.ptnr1_auth_asym_id
_struct_conn.ptnr1_label_asym_id
_struct_conn.ptnr1_label_comp_id
_struct_conn.ptnr1_label_seq_id
_struct_conn.ptnr1_label_atom_id
_struct_conn.pdbx_ptnr1_label_alt_id
_struct_conn.ptnr1_auth_seq_id
_struct_conn.pdbx_ptnr1_PDB_ins_code
_struct_conn.ptnr1_symmetry
_struct_conn.ptnr2_auth_asym_id
_struct_conn.ptnr2_label_asym_id
_struct_conn.ptnr2_label_comp_id
_struct_conn.ptnr2_label_seq_id
_struct_conn.ptnr2_label_atom_id
_struct_conn.pdbx_ptnr2_label_alt_id
_struct_conn.ptnr2_auth_seq_id
_struct_conn.pdbx_ptnr2_PDB_ins_code
_struct_conn.ptnr2_symmetry
_struct_conn.details
_struct_conn.pdbx_dist_value
_struct_conn.ccp4_link_id
? covale l lpoly 4D4 . C ? 81 ? 1_555 l lpoly MS6 . N1 ? 82 ? 1_555 ? 1.4237 4D4-MS6
? covale l lpoly MS6 . C ? 82 ? 1_555 l lpoly GLY . N ? 83 ? 1_555 ? 1.4250 MS6-GLY
```
I would not edit mmcif file manually! The latest Servalcat automatically puts these lines if bond distances in the model are sufficiently close to ideal values (threshold: 10%).

I tried COOT 0.9.6. VAL-4D4 and 4D4-MS6 links were ok (at least not broken) but MS6-GLY was broken. I need to ask Paul. Did Servalcat and Refmac work with the cif files?

IAS-pept link is already in CCP4 monomer library, so it should be fine for Refmac. I see Coot does not properly handle this. I need to ask Paul this as well.

**Comment by helgepat** [comment] 2022-02-01 08:04
> Did Servalcat and Refmac work with the cif files?

The job went through without crashing and so far I have not detected any major problems besides the VAL-4D4-MS6-GLY region: There is less rearrangement than before, but the MS6-GLY link is indeed not correct. Here are some screenshots of the region, one is with the diffmap:

![4D4-MS6-GLY](https://user-images.githubusercontent.com/97705752/151932520-923ee678-3850-4493-a86c-fb75d008a83d.png)

![diff_map](https://user-images.githubusercontent.com/97705752/151932561-426a24be-3c87-47f7-b0ff-87d5b5d59fa6.png)


I just went through the servalcat.log and have some comments/questions:

> Max residue number (10328) exceeds 9999. Will use mmcif format
That fix has worked well, as I had to use a .pdb file with my custom link records.

>  message: 'Warning: Desired error not necessarily achieved due to precision loss.'
Is this bad?

> Starting Refmac 5.8.0267 (PID: 2022771)
  WARNING: duplicated name of monomer 6MZ
  WARNING: duplicated name of monomer CA7
  WARNING: duplicated name of monomer IAS
  WARNING : CIS peptide bond is found, angle =     25.63
  WARNING : CIS peptide bond is found, angle =      7.73
  WARNING : CIS peptide bond is found, angle =      6.99
 Warning ==>The number of free reflections with flag         -999  is zero
 Warning ==> Switching off use of free R

Is there anything problematic here (besides the CIS peptides that I would have to check manually)?

**Comment by keitaroyam** [comment] 2022-02-01 08:12
Hmm, MS6-GLY is not correct. Were they connected in the input model? The latest Servalcat removes LINK record if the atoms are far. In this case you can disable this with `--no_link_check`.

What is the C-N distance of MS6 and GLY?

> Is this bad?

This should be fine (this is related to map masking).

> Is there anything problematic here (besides the CIS peptides that I would have to check manually)?

They also should be fine. Do you see a LINK record for MS6-GLY in refined.pdb?

**Comment by helgepat** [comment] 2022-02-01 08:40
> What is the C-N distance of MS6 and GLY?

The distance is 1.34A (see picture below)

![Distance](https://user-images.githubusercontent.com/97705752/151935645-6739cc80-b3fe-4712-a2cf-a4b485df99a1.png)

It seems that the distance between 4D4 and MS6 is quite high though.

> Were they connected in the input model?

I checked the input model (that had been refined in Coot using the monomer restraints) and I realize that it had already drifted from the PDB entry. You can see it in this screenshot (green: initial model; blue: PDB 7K00).

![initial_model](https://user-images.githubusercontent.com/97705752/151936743-efc7daf8-2e45-4003-a55f-e23ae140e506.png)



I actually do not see specific LINK records for the MS6-GLY (or any of the region for that matter). From refined.pdb:

SEQRES  14 g  176  THR LYS GLU ALA LYS LYS LYS                                  
LINKR        C   LYS L  44                 N   PRO L  45                PCIS    
LINKR        C   LYS L  44                 N   PRO L  45                PCIS    
LINKR        C   LYS L  44                 N   PRO L  45                PCIS    
CRYST1  388.800  388.800  388.800  90.00  90.00  90.00 P 1

**Comment by keitaroyam** [comment] 2022-02-01 08:57
OK, then COOT is the one that should be worked on. I guess the links would be kept if you give the original model to Servalcat.

**Comment by helgepat** [comment] 2022-02-01 09:01
So just to clarify, if I were to refine the initial PDB as is, the monomer restraints would be enough for servalcat or do I still have to provide the linked ones?

**Comment by keitaroyam** [comment] 2022-02-01 09:06
If you installed the github latest Servalcat 0.2.38 (through `pip install git+https://github.com/keitaroyam/servalcat.git`), you just need to give the PDB file as is.

**Comment by helgepat** [comment] 2022-02-01 09:11
Thats very cool, also thank you for all the help! I guess I need to find a way to identify issues like this after doing chain refine in Coot, because this only complains about restraints for the monomers and once those are provided it just runs...

**Closed as completed** 2022-02-01 09:12 UTC

**Comment by keitaroyam** [comment] 2022-02-01 09:18
You are welcome. Again I appreciate your feedback! I would post it here if I manage to keep the links in COOT.

**Comment by helgepat** [comment] 2022-02-01 10:00
Actually, looking at the diffmap would be ideal to spot such issues (if refmac cannot fix what was broken before ;)). Case in point would be that I detected it using servalcat in the first place!

**Comment by keitaroyam** [comment] 2022-02-18 10:38
Update: monomer library (on the code repository) now includes all these monomers and related links (MS6-pept/pept-MS6/4D4-pept/pept-4D4) https://fg.oisin.rc-harwell.ac.uk/scm/loggerhead/monomers/trunk/revision/202 (with the help of Rob). They will be available in CCP4 in the next update.

Paul has confirmed there is a problem with the link in COOT. He is now looking into it.

**Comment by helgepat** [comment] 2022-02-18 11:23
Amazing! Thanks again for your effort!

**Comment by keitaroyam** [comment] 2022-03-28 15:25
We found that COOT had a special requirement for linking. Group names should be consistent among definitions of monomers, modifications, and links. For example in https://github.com/keitaroyam/servalcat/issues/4#issuecomment-1025646594 `_chem_mod.group_id` were all "." but they should be filled with corresponding group names. It is fixed in the latest version of Acedrg (ver 243) which will be distributed with CCP4 8.0 (I think).

For now, this file [4D4_MS6_IAS_merged.zip](https://github.com/keitaroyam/servalcat/files/8364147/4D4_MS6_IAS_merged.zip) can be used for COOT. This also fixes IAS linking problem.
