### ISSUE TITLE
Adjusting weight or disabling non-crystallographic symmetry restraints (NCS restraints) 

### ISSUE THREAD

**Issue by daniel-s-d-larsson** [keitaroyam/servalcat#17] opened 2024-08-21 12:02 UTC
Is it possible to disable NCS restraints or adjusting the weights (setting them to e.g. zero)? It seems they are found and applied by default? Is that desired? I could imagine two copies of the same molecule adopting two rather different conformations and that one would not necessary want to have NCS restraints. And the B-factors could be very different for them.

The servalcat documentation shows that you can select between local and global. I think I understand the meaning of local, to make equivalent regions for each macromolecule look locally similar, but what does global mean? The Refmac5 documentation only explains what local mean.

**Comment by keitaroyam** [comment] 2024-08-21 12:30
In refine_spa_norefmac, the NCS restraint is an optional feature activated by the --ncsr option. It uses a robust function to allow for conformational differences, but may not always be beneficial. The NCS restraint only applies to atomic coordinates. 

The global NCS restraint, which is not implemented in servalcat, aims to make overall structures more similar by applying restraints based on the RMSD between atoms of aligned chains.

**Comment by daniel-s-d-larsson** [comment] 2024-08-21 12:53
Do I understand it correctly that NCS restraints will not be applied with this command: 

`servalcat refine_spa_norefmac --halfmaps A.mrc B.mrc --model model.cif --resolution 2.5`

And with this command NCS restraints will be applied for chains with identical sequences

`servalcat refine_spa_norefmac --halfmaps A.mrc B.mrc --model model.cif --resolution 2.5 --ncsr local`

**Comment by keitaroyam** [comment] 2024-08-21 13:23
Correct, the NCS restraints will not be applied without --ncsr. In refine_spa_norefmac, --ncsr does not accept any additional keywords, so `--ncsr local` would fail.

It seems that servalcat produced unexpected results, and you suspected that NCS restraints were the cause? More information about the specific issues you encountered would be helpful in identifying the root problem.

**Comment by daniel-s-d-larsson** [comment] 2024-08-22 07:12
Ok, thanks for confirming. I just now realize that the help command for `servalcat refine_spa_norefmac --help` has this documented. I thought that refine_spa_norefmac was a drop-in replacement for refine_spa with identical set of input parameters, but apparently it is not.

The problem we encountered related to NCS restraints was that an older versions of servalcat/refmac shipped with CCP4-8 did not write a proper .mmcif header (and it was not written in the log files either as far as we could tell). Therefore the wwPDB annotator complained that the NCS groups were not defined. The versions of servalcat/refmac shipped with CCP4-9 seems to have fixed this and the ncsr chains are defined in the .mmcif header.

It seems as if refine_spa_norefmac is the superior binary in all kinds of ways. You should add documentation about it on the readthedocs page [https://servalcat.readthedocs.io/en/latest/commands.html#](url).

**Comment by daniel-s-d-larsson** [comment] 2024-08-22 07:36
I see that refine_spa_norefmac has a flag `--contacting_only   Filter out non-contacting NCS` which would make sense in cases where two chains bind in different parts of the complex.

I'm curious to what these flags do:
`--jellyonly`
`--no_weight_adjust`
`--adpr_weight ADPR_WEIGHT`
`--fix_xyz`
`--keep_entities`

Why does refine_spa_norefmac not have the parameter `--weight_auto_scale WEIGHT_AUTO_SCALE`?

**Comment by keitaroyam** [comment] 2024-08-23 07:13
Yes, Refmac's ncsr mmcif issue was fixed in CCP4 9.0.002.

OK, I have updated the documentation. I basically made refine_spa_norefmac compatible with refine_spa, but I changed some keywords if they made more sense.

`--contacting_only` is a different stuff: this may be useful when refining huge complex with high symmetry (e.g., icosahedral). It trims maps around the ASU model and contacting copies to speed up calculations.

`--jellyonly` is an experimental feature that disables all restraints except for jelly-body restraints. This might allow for a larger radius of convergence in the early stages of crystallographic refinement.

`--no_weight_adjust` prevents the automatic adjustment of weight based on bond length RMSD, preserving the initial (or user-provided) weight value.

`--adpr_weight` changes the weight of ADP restraints. `--fix_xyz` prevents the refinement of coordinates. `--keep_entities` preserves the entity information in the input mmcif file (instead of letting gemmi re-determine entities).

`--weight_auto_scale` in refine_spa and `--weight` in refine_spa_norefmac are essentially the same option. I changed the name to `--weight` because "weight_auto_scale" was misleading, as it implied specifying a scale for automatically determined weight.

**Comment by daniel-s-d-larsson** [comment] 2024-08-27 12:48
How does the automatic map weighting work? From reading refmac documentation, my understanding is that a weight is first guessed based on the resolution of the reconstruction and the ratio between the model size and the box size (using some unknown heuristics, which perhaps requires reading the source code to understand). Then it will choose a map weight so that the bond lenght RMSD gets a specific value, e.g. 0.01. Is that correct? In my experience the bond length RMSD ends up in the range 90-115 with automatic map weight.

My understanding was that `--weight_auto_scale` was a scalar value which was multiplied with the automatically determined map weight. But you say that is not the case?

If `--weight` is not for directly setting the map weight in `refine_spa_norefmac`, then how does one set the map weight manually?

**Comment by daniel-s-d-larsson** [comment] 2024-08-27 13:16
Is `--fix_xyz` similar to `--keywords "refi bonly"` which I saw was a way to only refine the ADPs? https://github.com/keitaroyam/servalcat/issues/4

**Comment by keitaroyam** [comment] 2024-08-28 06:44
Yes, unless the weight (I would not call this a map weighting, as it works in Fourier space) is specified by user, it is calculated based on the resolution and volume ratio. This empirical relationship was established by refining PDB/EMDB entries. The weight is dynamically adjusted during refinement cycles, increasing when the bond length RMSZ is low and decreasing when it is high. However, this adjustment does not guarantee achieving a specific target RMSZ.

What did you mean by 90-115, which do not look like bond length rmsd value?

> My understanding was that --weight_auto_scale was a scalar value which was multiplied with the automatically determined map weight. But you say that is not the case?

This is exactly how I misunderstood. The value after `--weight_auto_scale` (given to refmac5 as `weight auto <value>`) is used as a weight value.

> If --weight is not for directly setting the map weight in refine_spa_norefmac, then how does one set the map weight manually?

--weight is for directly setting the weight.

> Is --fix_xyz similar to --keywords "refi bonly" which I saw was a way to only refine the ADPs? #4

Yes!

**Comment by daniel-s-d-larsson** [comment] 2024-09-09 11:53
The numbers should have been bond length RMSD of 0.0090-0.0115 Å. I seen that the value varies quite a lot between runs.

**Comment by keitaroyam** [comment] 2024-09-11 07:19
The bond length RMSD of 0.0090-0.0115 Å falls within the target range and is generally considered acceptable. However, smaller RMSD values may be preferred in certain scenarios, such as at lower resolutions. You can always play with --weight and/or --target_bond_rmsz_range (default is 0.5 1).

**Comment by daniel-s-d-larsson** [comment] 2024-09-26 08:39
So, is the automatic map weighting algorithm targeting the RMSZ range rather than the RMSD?

**Comment by keitaroyam** [comment] 2024-09-26 08:40
Yes.

**Comment by keitaroyam** [comment] 2024-10-25 13:28
I'm closing this. Please reopen or create a new issue if you find any further problems.

**Closed as completed by keitaroyam** 2024-10-25 13:28 UTC
